# Generated by Django 4.1.7 on 2023-02-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='description',
        ),
    ]
